services:
  dv-ros2:
    image: ros2_dv_ros2:latest
    container_name: dv-ros2
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    tty: true
    privileged: true
    command: ros2 launch dv_ros2_visualization all.launch.py