dv_ros2_tracker:
  ros__parameters:
    # Enable the use of event data, at least one event or frame input has to be enabled
    use_events: true
    # Enable the use of frame data, at least one event or frame input has to be enabled
    use_frames: false
    # Maximum number of features to track
    max_tracks: 300
    # Number of pyramid layers to use for Lucas-Kanade tracking
    num_pyr_layers: 4
    # Track termination epsilon for Lucas-Kanade tracking
    termination_epsilon: 0.001
    # Perform backward tracking and reject any tracks that don't "track-back" to original location
    lookback_rejection: false
    # Search window size, this value is used for both x and y sizes
    search_window_size: 24
    # Mask out regions of image where tracked features are present
    masked_feature_detect: true
    # When tracked amount of features reached this threshold (proportion of maxTracks), new features will be detected
    redetection_threshold: 0.75
    # FAST corner detector threshold
    fast_threshold: 10
    # Number of events accumulated in a single frame
    num_events: 30000
    # Frame accumulation framerate
    accumulation_framerate: 100
    # Combined mode uses accumulated frame to perform intermediate tracking between image frames, this value controls how many frames are accumulated between two image frames
    num_intermediate_frames: 5
    # MotionAware Tracker
    use_motion_compensation: false
          